### PR TITLE
Propagate retry operation from `Set` resources to child resources

### LINKED ISSUE #473: Annotation to retry all the Failed child Resources
BIOS/BMC Setting/Version Set Resources create child object which might end up in failed state. 

Provide as ability to create a re-try annotation which will be propogated to the child object and restart the failed child resources.

### PR DESCRIPTION
**Pull request by nagadeesh-nagaraja**
Fixes #473

### CODE REVIEW

File: internal/controller/biossettingsset_controller.go [hunk 1]
```diff
@@ -162,8 +167,68 @@ func (r *BIOSSettingsSetReconciler) handleIgnoreAnnotationPropagation(
...
+					annotations := biosSettings.GetAnnotations()
+					log.V(1).Info("Retry operation deleted on child object", "BIOSSettings", biosSettings.Name)
+					delete(annotations, metalv1alpha1.OperationAnnotation)
+					delete(annotations, metalv1alpha1.OperationAnnotationPropagated)
+					biosSettings.SetAnnotations(annotations)
+				}
+				return nil
+			})
+			if err != nil {
+				errs = append(errs, fmt.Errorf("failed to patch BIOSSettings annotations Propogartion removal: %w for: %v", err, biosSettings.Name))
```
Comment (Nuckal777) [inline internal/controller/biossettingsset_controller.go]: typo in `propagation`

File: internal/controller/biossettingsset_controller.go [hunk 2]
```diff
@@ -100,6 +100,11 @@ func (r *BIOSSettingsSetReconciler) delete(
 		if err != nil {
 			return ctrl.Result{}, fmt.Errorf("failed to update current BIOSSettingsSet Status %w", err)
 		}
+		// handle propagartion of retry annotation to child when parent is being deleted
```
Comment (Nuckal777) [inline internal/controller/biossettingsset_controller.go]: typo in propagation

**Review by Nuckal777 — APPROVED** [review]
PR is fine from my side. @afritzler maybe you want to take another look?

File: api/v1alpha1/constants.go [hunk 3]
```diff
@@ -3,27 +3,75 @@
...
+	GracefulRestartServerPower: redfish.OnResetType,
+	HardRestartServerPower:     redfish.ForceRestartResetType,
+	PowerCycleServerPower:      redfish.PowerCycleResetType,
+	ForceOffServerPower:        redfish.ForceOffResetType,
+	ForceOnServerPower:         redfish.ForceOnResetType,
+}
+
+const (
+	// ForceResetBMCOperationAnnotation forces a reset of BMC before next operation
+	ForceResetBMCOperationAnnotation = "force-reset-BMC"
```
Comment (afritzler) [inline api/v1alpha1/constants.go]: Do we need an own force reset operation for BMCs? Why not just having a global `force-reset` operation for all applicable resources?

**Review by afritzler — CHANGES_REQUESTED** [review]
Looks good from my side - some minor things. Just as a side node, why do decided to go with a dedicated `ForceReset` annotation value for BMCs? I can't remember anymore.

File: api/v1alpha1/constants.go (hunk 3 above)
Comment (nagadeesh-nagaraja) [reply api/v1alpha1/constants.go]: I am guessing that, this was named different (and was not using the regular reset operation similar to server) because initial idea was this does both, tries regular reset of server, if not then force reset. this was suppose to be one operation doing everything? 
but while we figure out the kubeConfig seperation to run jobs, this was probably left behind... 

Should I change it back to this? 
`OperationAnnotationForceReset = "ForceReset"`

currently, this is only handled in BMC controller which is doing graceful reset ( server resource uses its own operation)

**Review by afritzler — CHANGES_REQUESTED** [review]
