### PR TITLE
Fix update/patch logic for BIOS/BMC set child resources 

### LINKED ISSUE #436: `BIOSSettingsSet` does not update status all the time
**Describe the bug**
The biosSettingsSet fails to show the correct status

**To Reproduce**
create biosSettingsSet, observe the status

**Expected behavior**
to update the status all the time

when not updating correctly
```
(eu-de-2|k=a-eu-de-2)I760727@CXRLFLKF6L:~/Workspace/remoteboard_password_rotator%kubectl get biossettings   
NAME                                                    BIOSVERSION   SERVERREF                SERVERMAINTENANCEREF   STATE     APPLIEDON   AGE
biossettingsset-poweredge-r640-node012-ap048-system-0   2.22.2        node012-ap048-system-0                                                3m46s
biossettingsset-poweredge-r640-node012-ap049-system-0   2.22.2        node012-ap049-system-0                                                3m46s
biossettingsset-poweredge-r640-node013-ap048-system-0   2.22.2        node013-ap048-system-0                                                3m46s
biossettingsset-poweredge-r640-node013-ap049-system-0   2.22.2        node013-ap049-system-0                                                3m46s
biossettingsset-poweredge-r640-node014-ap049-system-0   2.22.2        node014-ap049-system-0                                                3m46s
biossettingsset-poweredge-r640-node015-ap048-system-0   2.22.2        node015-ap048-system-0                          Applied   3m38s       3m46s
biossettingsset-poweredge-r640-node018-ap048-system-0   2.22.2        node018-ap048-system-0                          Applied   29s         3m46s
biossettingsset-poweredge-r640-node019-ap049-system-0   2.22.2        node019-ap049-system-0                                                3m46s
biossettingsset-poweredge-r640-node020-ap048-system-0   2.22.2        node020-ap048-system-0                                                3m46s
biossettingsset-poweredge-r640-node020-ap049-system-0   2.22.2        node020-ap049-system-0                                                3m46s
(eu-de-2|k=a-eu-de-2)I760727@CXRLFLKF6L:~/Workspace/remoteboard_password_rotator%kubectl get biossettingsset
NAME                             BIOSVERSION   TOTALSERVERS   AVAILABLEBIOSSETTINGS   PENDING   INPROGRESS   COMPLETED   FAILED   AGE
biossettingsset-poweredge-r640   2.22.2                                                                                           3m51s
```

when working correctly:
```
(eu-de-2|k=a-eu-de-2)I760727@CXRLFLKF6L:~/Workspace/remoteboard_password_rotator%kubectl get biossettingsset                                                             
NAME                             BIOSVERSION   TOTALSERVERS   AVAILABLEBIOSSETTINGS   PENDING   INPROGRESS   COMPLETED   FAILED   AGE
biossettingsset-poweredge-r640   2.22.2        10             10                      5                      5                    6m31s
(eu-de-2|k=a-eu-de-2)I760727@CXRLFLKF6L:~/Workspace/remoteboard_password_rotator%kubectl get biossettings                                                                
NAME                                                    BIOSVERSION   SERVERREF                SERVERMAINTENANCEREF   STATE     APPLIEDON   AGE
biossettingsset-poweredge-r640-node012-ap048-system-0   2.22.2        node012-ap048-system-0                                                6m34s
biossettingsset-poweredge-r640-node012-ap049-system-0   2.22.2        node012-ap049-system-0                                                6m34s
biossettingsset-poweredge-r640-node013-ap048-system-0   2.22.2        node013-ap048-system-0                                                6m34s
biossettingsset-poweredge-r640-node013-ap049-system-0   2.22.2        node013-ap049-system-0                          Applied   99s         6m34s
biossettingsset-poweredge-r640-node014-ap049-system-0   2.22.2        node014-ap049-system-0                          Applied   95s         6m34s
biossettingsset-poweredge-r640-node015-ap048-system-0   2.22.2        node015-ap048-system-0                          Applied   6m26s       6m34s
biossettingsset-poweredge-r640-node018-ap048-system-0   2.22.2        node018-ap048-system-0                          Applied   3m17s       6m34s
biossettingsset-poweredge-r640-node019-ap049-system-0   2.22.2        node019-ap049-system-0                          Applied   110s        6m34s
biossettingsset-poweredge-r640-node020-ap048-system-0   2.22.2        node020-ap048-system-0                                                6m34s
biossettingsset-poweredge-r640-node020-ap049-system-0   2.22.2        node020-ap049-system-0                                                6m34s
```

**Screenshots**
```
2025-08-15T10:36:44Z	ERROR	Observed a panic	{"controller": "biossettingsset", "controllerGroup": "metal.ironcore.dev", "controllerKind": "BIOSSettingsSet", "BIOSSettingsSet": {"name":"biossettingsset-poweredge-r640"}, "namespace": "", "name": "biossettingsset-poweredge-r640", "reconcileID": "710e06ac-9134-4ff0-bd1d-cd4c36daec4d", "panic": "runtime error: invalid memory address or nil pointer dereference", "panicGoValue": "\"invalid memory address or nil pointer dereference\"", "stacktrace": "goroutine 539 [running]:\nk8s.io/apimachinery/pkg/util/runtime.logPanic({0x2865fe8, 0xc000dfc690}, {0x209f720, 0x3d3b920})\n\t/go/pkg/mod/k8s.io/apimachinery@v0.33.3/pkg/util/runtime/runtime.go:132 +0xbc\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile.func1()\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/controller/controller.go:108 +0x112\npanic({0x209f720?, 0x3d3b920?})\n\t/usr/local/go/src/runtime/panic.go:792 +0x132\ngithub.com/ironcore-dev/metal-operator/internal/controller.(*BIOSSettingsSetReconciler).deleteOrphanBIOSSettings(0xc0006a35a8, {0x2865fe8, 0xc000dfc690}, {{0x2870658?, 0xc000dfc6c0?}, 0xc001396a80?}, 0xc00029bb90, 0xc000329180)\n\t/workspace/internal/controller/biossettingsset_controller.go:223 +0x127\ngithub.com/ironcore-dev/metal-operator/internal/controller.(*BIOSSettingsSetReconciler).handleBiosSettings(0xc0006a35a8, {0x2865fe8, 0xc000dfc690}, {{0x2870658?, 0xc000dfc6c0?}, 0xc000fb4600?}, 0xc00029bb90, 0xc000fb4600)\n\t/workspace/internal/controller/biossettingsset_controller.go:151 +0x259\ngithub.com/ironcore-dev/metal-operator/internal/controller.(*BIOSSettingsSetReconciler).reconcile(0xc0006a35a8, {0x2865fe8, 0xc000dfc690}, {{0x2870658?, 0xc000dfc6c0?}, 0x0?}, 0xc000fb4600)\n\t/workspace/internal/controller/biossettingsset_controller.go:129 +0x178\ngithub.com/ironcore-dev/metal-operator/internal/controller.(*BIOSSettingsSetReconciler).reconcileExists(0x2870658?, {0x2865fe8?, 0xc000dfc690?}, {{0x2870658?, 0xc000dfc6c0?}, 0x0?}, 0x0?)\n\t/workspace/internal/controller/biossettingsset_controller.go:64 +0x106\ngithub.com/ironcore-dev/metal-operator/internal/controller.(*BIOSSettingsSetReconciler).Reconcile(0xc0006a35a8, {0x2865fe8, 0xc000dfc690}, {{{0x0?, 0x24be0d2?}, {0xc000447720?, 0x100?}}})\n\t/workspace/internal/controller/biossettingsset_controller.go:50 +0x1b6\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile(0xc000dfc600?, {0x2865fe8?, 0xc000dfc690?}, {{{0x0?, 0x0?}, {0xc000447720?, 0x0?}}})\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/controller/controller.go:119 +0xbf\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler(0x28988e0, {0x2866020, 0xc000320320}, {{{0x0, 0x0}, {0xc000447720, 0x1e}}}, 0x0)\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/controller/controller.go:340 +0x3ad\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem(0x28988e0, {0x2866020, 0xc000320320})\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/controller/controller.go:300 +0x21b\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.1()\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/controller/controller.go:202 +0x85\ncreated by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2 in goroutine 289\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/controller/controller.go:198 +0x28f\n"}
k8s.io/apimachinery/pkg/util/runtime.logPanic
	/go/pkg/mod/k8s.io/apimachinery@v0.33.3/pkg/util/runtime/runtime.go:142
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/controller/controller.go:108
runtime.gopanic
	/usr/local/go/src/runtime/panic.go:792
runtime.panicmem
	/usr/local/go/src/runtime/panic.go:262
runtime.sigpanic
	/usr/local/go/src/runtime/signal_unix.go:925
github.com/ironcore-dev/metal-operator/internal/controller.(*BIOSSettingsSetReconciler).deleteOrphanBIOSSettings
	/workspace/internal/controller/biossettingsset_controller.go:223
github.com/ironcore-dev/metal-operator/internal/controller.(*BIOSSettingsSetReconciler).handleBiosSettings
	/workspace/internal/controller/biossettingsset_controller.go:151
github.com/ironcore-dev/metal-operator/internal/controller.(*BIOSSettingsSetReconciler).reconcile
	/workspace/internal/controller/biossettingsset_controller.go:129
github.com/ironcore-dev/metal-operator/internal/controller.(*BIOSSettingsSetReconciler).reconcileExists
	/workspace/internal/controller/biossettingsset_controller.go:64
github.com/ironcore-dev/metal-operator/internal/controller.(*BIOSSettingsSetReconciler).Reconcile
	/workspace/internal/controller/biossettingsset_controller.go:50
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/controller/controller.go:119
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/controller/controller.go:340
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/controller/controller.go:300
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/controller/controller.go:202
2025-08-15T10:36:44Z	ERROR	Reconciler error	{"controller": "biossettingsset", "controllerGroup": "metal.ironcore.dev", "controllerKind": "BIOSSettingsSet", "BIOSSettingsSet": {"name":"biossettingsset-poweredge-r640"}, "namespace": "", "name": "biossettingsset-poweredge-r640", "reconcileID": "710e06ac-9134-4ff0-bd1d-cd4c36daec4d", "error": "panic: runtime error: invalid memory address or nil pointer dereference [recovered]"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/controller/controller.go:353
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/controller/controller.go:300
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/controller/controller.go:202
```

### PR DESCRIPTION
**Pull request by nagadeesh-nagaraja**
# Proposed Changes

Add spec update logic for all set resources, 
fix create BIOS settings when server has exisiitng BIOSSettings ref.
Handle graceful deletion when force deleted (with removed finalizer)

Fixes #436 #435 #434

### CODE REVIEW

File: internal/controller/biossettingsset_controller.go [hunk 1]
```diff
@@ -239,6 +248,35 @@ func (r *BIOSSettingsSetReconciler) deleteOrphanBIOSSettings(
 	return errors.Join(errs...)
 }
 
+func (r *BIOSSettingsSetReconciler) updateSpec(
```
Comment (afritzler) [inline internal/controller/biossettingsset_controller.go:251]: Can we call this method `patchOrCreateBIOSSettingsfromTemplate` and only pass the template + the set list?

File: internal/controller/biosversionset_controller.go [hunk 2]
```diff
@@ -229,6 +234,35 @@ func (r *BIOSVersionSetReconciler) deleteOrphanBIOSVersions(
 	return warnings, errors.Join(errs...)
 }
 
+func (r *BIOSVersionSetReconciler) updateSpec(
```
Comment (afritzler) [inline internal/controller/biosversionset_controller.go:237]: I would use a similar naming convention here: `patchOrCreateBIOSVersionFromTemplate`.

File: internal/controller/bmcversionset_controller.go [hunk 3]
```diff
@@ -216,6 +221,35 @@ func (r *BMCVersionSetReconciler) deleteOrphanBMCVersions(
 	return warnings, errors.Join(errs...)
 }
 
+func (r *BMCVersionSetReconciler) updateSpec(
```
Comment (afritzler) [inline internal/controller/bmcversionset_controller.go:224]: Same here.

**Review by afritzler — CHANGES_REQUESTED** [review]

File: internal/controller/biosversionset_controller.go [hunk 4]
```diff
@@ -229,6 +230,42 @@ func (r *BIOSVersionSetReconciler) deleteOrphanBIOSVersions(
...
+	biosVersionList *metalv1alpha1.BIOSVersionList,
+) error {
+	if len(biosVersionList.Items) == 0 {
+		log.V(1).Info("No BIOSVersion found, skipping spec template update")
+		return nil
+	}
+
+	var errs []error
+	for _, biosVersion := range biosVersionList.Items {
+		if biosVersion.Status.State != metalv1alpha1.BIOSVersionStateInProgress {
```
Comment (stefanhipfel) [inline internal/controller/biosversionset_controller.go:246]: since there is no `else`, we could check for in progress and use continue?
```
if biosVersion.Status.State == metalv1alpha1.BIOSVersionStateInProgress {
  continue
}
```

File: internal/controller/bmcversionset_controller.go [hunk 5]
```diff
@@ -216,6 +216,35 @@ func (r *BMCVersionSetReconciler) deleteOrphanBMCVersions(
...
+	bmcVersionList *metalv1alpha1.BMCVersionList,
+) error {
+	if len(bmcVersionList.Items) == 0 {
+		log.V(1).Info("No BMCVersion found, skipping spec template update")
+		return nil
+	}
+
+	var errs []error
+	for _, bmcVersion := range bmcVersionList.Items {
+		if bmcVersion.Status.State != metalv1alpha1.BMCVersionStateInProgress {
```
Comment (stefanhipfel) [inline internal/controller/bmcversionset_controller.go:232]: same as above

File: internal/controller/biossettingsset_controller.go [hunk 6]
```diff
@@ -141,16 +140,18 @@ func (r *BIOSSettingsSetReconciler) handleBiosSettings(
 	}
 
 	if err := r.createMissingBIOSSettings(ctx, log, serverList, ownedBiosSettings, biosSettingsSet); err != nil {
```
Comment (stefanhipfel) [inline internal/controller/biossettingsset_controller.go:142]: can't we use the same func `patchOrCreateBIOSSettingsfromTemplate`, since it also creates BIOSSettings as well..

**Review by stefanhipfel — APPROVED** [review]
